name: Noctis
version: "1.0.0"
main: org.ReDiego0.noctis.Noctis
api-version: '1.21'
depend: [Towny]
softdepend: [Vault, PlaceholderAPI, MythicMobs, Citizens, FastAsyncWorldEdit]
permissions:
  noctis.admin.*:
    description: Permisos de admin
    default: op